In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-03-21 14:43:14
# @Author  : guanglinzhou (xdzgl812@163.com)
# @Link    : https://github.com/GuanglinZhou
# @Version : $Id$

import os
import numpy as np
import pandas as pd

In [6]:
def loadDataSet():
    dataMat = []
    labelMat = []
    fr = open('data.csv')
    for line in fr.readlines():
        lineArr = line.strip().split(',')
        dataMat.append(float(lineArr[0]))
        labelMat.append(float(lineArr[1]))
    return dataMat, labelMat

In [7]:
if __name__ == '__main__':
    learning_rate = 0.1
    dataMat, labelMat = loadDataSet()

In [9]:
dataMat

[32.50234526945303,
 53.42680403327502,
 61.53035802563644,
 47.4756396347861,
 59.81320786951232,
 55.14218841394382,
 52.211796692214,
 39.299566694317065,
 48.10504169176825,
 52.55001444273382,
 45.419730144973755,
 54.35163488122892,
 44.16404949677335,
 58.16847071685779,
 56.72720805709661,
 48.95588856609372,
 44.687196231480904,
 60.297326851333466,
 45.61864377295583,
 38.81681753744564,
 66.1898166067526,
 65.41605174513407,
 47.48120860786787,
 41.57564261748702,
 51.84518690563943,
 59.37082201108952,
 57.31000343834809,
 63.61556125145331,
 46.73761940797697,
 50.55676014854777,
 52.22399608555305,
 35.56783004774663,
 42.43647694405564,
 58.16454011019286,
 57.50444761534179,
 45.44053072531998,
 61.89622268029126,
 33.09383173616396,
 36.43600951138687,
 37.67565486085074,
 44.555608383275356,
 43.31828263186572,
 50.073145632289034,
 43.87061264521837,
 62.99748074755309,
 32.66904376346719,
 40.1668990087037,
 53.57507753167366,
 33.86421497177824,
 64.7071386661213,


In [11]:
dataMatrix = np.mat(dataMat)
yMatrix = np.mat(labelMat)

In [12]:
dataMatrix

matrix([[ 32.50234527,  53.42680403,  61.53035803,  47.47563963,
          59.81320787,  55.14218841,  52.21179669,  39.29956669,
          48.10504169,  52.55001444,  45.41973014,  54.35163488,
          44.1640495 ,  58.16847072,  56.72720806,  48.95588857,
          44.68719623,  60.29732685,  45.61864377,  38.81681754,
          66.18981661,  65.41605175,  47.48120861,  41.57564262,
          51.84518691,  59.37082201,  57.31000344,  63.61556125,
          46.73761941,  50.55676015,  52.22399609,  35.56783005,
          42.43647694,  58.16454011,  57.50444762,  45.44053073,
          61.89622268,  33.09383174,  36.43600951,  37.67565486,
          44.55560838,  43.31828263,  50.07314563,  43.87061265,
          62.99748075,  32.66904376,  40.16689901,  53.57507753,
          33.86421497,  64.70713867,  38.11982403,  44.50253806,
          40.59953838,  41.72067636,  51.08863468,  55.0780959 ,
          41.37772653,  62.49469743,  49.20388754,  41.10268519,
          41.18201611,  5

In [17]:
yMatrix.shape

(1, 100)

In [18]:
w=np.ones((10,2))

In [19]:
w

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [20]:
dataMat = [];
labelMat = []
fr = open('/Users/guanglinzhou/Documents/GitHub/MachinelearningInaction/Ch05/testSet.txt')
for line in fr.readlines():
    lineArr = line.strip().split()
    dataMat.append([1.0, float(lineArr[0]), float(lineArr[1])])
    labelMat.append(int(lineArr[2]))

In [21]:

def sigmoid(inX):
    return 1.0 / (1 + exp(-inX))

In [23]:
dataMat

[[1.0, -0.017612, 14.053064],
 [1.0, -1.395634, 4.662541],
 [1.0, -0.752157, 6.53862],
 [1.0, -1.322371, 7.152853],
 [1.0, 0.423363, 11.054677],
 [1.0, 0.406704, 7.067335],
 [1.0, 0.667394, 12.741452],
 [1.0, -2.46015, 6.866805],
 [1.0, 0.569411, 9.548755],
 [1.0, -0.026632, 10.427743],
 [1.0, 0.850433, 6.920334],
 [1.0, 1.347183, 13.1755],
 [1.0, 1.176813, 3.16702],
 [1.0, -1.781871, 9.097953],
 [1.0, -0.566606, 5.749003],
 [1.0, 0.931635, 1.589505],
 [1.0, -0.024205, 6.151823],
 [1.0, -0.036453, 2.690988],
 [1.0, -0.196949, 0.444165],
 [1.0, 1.014459, 5.754399],
 [1.0, 1.985298, 3.230619],
 [1.0, -1.693453, -0.55754],
 [1.0, -0.576525, 11.778922],
 [1.0, -0.346811, -1.67873],
 [1.0, -2.124484, 2.672471],
 [1.0, 1.217916, 9.597015],
 [1.0, -0.733928, 9.098687],
 [1.0, -3.642001, -1.618087],
 [1.0, 0.315985, 3.523953],
 [1.0, 1.416614, 9.619232],
 [1.0, -0.386323, 3.989286],
 [1.0, 0.556921, 8.294984],
 [1.0, 1.224863, 11.58736],
 [1.0, -1.347803, -2.406051],
 [1.0, 1.196604, 4.951851]

In [26]:
labelMat

[0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0]

In [28]:
from numpy import *
dataMatrix = mat(dataMat)  # convert to NumPy matrix
labelMat = mat(labelMat).transpose()  # convert to NumPy matrix

In [29]:
dataMatrix

matrix([[  1.00000000e+00,  -1.76120000e-02,   1.40530640e+01],
        [  1.00000000e+00,  -1.39563400e+00,   4.66254100e+00],
        [  1.00000000e+00,  -7.52157000e-01,   6.53862000e+00],
        [  1.00000000e+00,  -1.32237100e+00,   7.15285300e+00],
        [  1.00000000e+00,   4.23363000e-01,   1.10546770e+01],
        [  1.00000000e+00,   4.06704000e-01,   7.06733500e+00],
        [  1.00000000e+00,   6.67394000e-01,   1.27414520e+01],
        [  1.00000000e+00,  -2.46015000e+00,   6.86680500e+00],
        [  1.00000000e+00,   5.69411000e-01,   9.54875500e+00],
        [  1.00000000e+00,  -2.66320000e-02,   1.04277430e+01],
        [  1.00000000e+00,   8.50433000e-01,   6.92033400e+00],
        [  1.00000000e+00,   1.34718300e+00,   1.31755000e+01],
        [  1.00000000e+00,   1.17681300e+00,   3.16702000e+00],
        [  1.00000000e+00,  -1.78187100e+00,   9.09795300e+00],
        [  1.00000000e+00,  -5.66606000e-01,   5.74900300e+00],
        [  1.00000000e+00,   9.31635000e

In [31]:
labelMat

matrix([[0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],

In [32]:
m, n = shape(dataMatrix)
alpha = 0.001
maxCycles = 500
weights = ones((n, 1))

In [33]:
weights

array([[ 1.],
       [ 1.],
       [ 1.]])

In [34]:
m

100